# This is a basic workflow to help you get started with Actions

name: Fork Sync

# Runs at 13:00 UTC every day
on:
  schedule:
    - cron: '0 13 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # sync with upstream
    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'speckleworks'
      - uses: actions/checkout@v2
      - run: |
          git remote add upstream https://github.com/speckleworks/SpeckleServer.git
          git fetch upstream
          git remote set-url origin https://peterjgrainger:${{ secrets.GITHUB_TOKEN }}@github.com/arup-group/SpeckleServer.git
          git push origin --tags

