# This is a basic workflow to help you get started with Actions

name: Apply All Regions

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag to deploy (without the v)
        required: true
        default: '1.9.10'
      ansibleScriptsBranch:
        description: branch of the  global-speckle-server-ansible-playbooks repos
        required: true
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        region: ['ireland', 'hongkong', 'australia', 'uk', 'canada']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Speckle Server to production in all regions
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to Production Environment
          token: ${{ secrets.REPO_FULL_ACCESS }}
          inputs: '{ "tag": "${{ github.event.inputs.tag }}", "ansibleScriptsBranch":"${{ github.event.inputs.ansibleScriptsBranch }}", "region": "${{ matrix.region }}" }'
        
